"""обновил поле датывремя для HabitLog

Revision ID: ac3a384dfa7f
Revises: 33f8488195b6
Create Date: 2025-09-17 20:08:10.745423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3a384dfa7f'
down_revision: Union[str, None] = '33f8488195b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('habit_logs', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('habit_logs', 'completed_at')
    # ### end Alembic commands ###
